#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROYECTO_POO")]
	public partial class Bd_POODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCERTIFICADOS_PROFESORES(CERTIFICADOS_PROFESORES instance);
    partial void UpdateCERTIFICADOS_PROFESORES(CERTIFICADOS_PROFESORES instance);
    partial void DeleteCERTIFICADOS_PROFESORES(CERTIFICADOS_PROFESORES instance);
    partial void InsertDETALLE_MATRICULA(DETALLE_MATRICULA instance);
    partial void UpdateDETALLE_MATRICULA(DETALLE_MATRICULA instance);
    partial void DeleteDETALLE_MATRICULA(DETALLE_MATRICULA instance);
    partial void InsertESTUDIANTES(ESTUDIANTES instance);
    partial void UpdateESTUDIANTES(ESTUDIANTES instance);
    partial void DeleteESTUDIANTES(ESTUDIANTES instance);
    partial void InsertHORARIO_P(HORARIO_P instance);
    partial void UpdateHORARIO_P(HORARIO_P instance);
    partial void DeleteHORARIO_P(HORARIO_P instance);
    partial void InsertMATERIAS(MATERIAS instance);
    partial void UpdateMATERIAS(MATERIAS instance);
    partial void DeleteMATERIAS(MATERIAS instance);
    partial void InsertMATERIAS_ABIERTAS(MATERIAS_ABIERTAS instance);
    partial void UpdateMATERIAS_ABIERTAS(MATERIAS_ABIERTAS instance);
    partial void DeleteMATERIAS_ABIERTAS(MATERIAS_ABIERTAS instance);
    partial void InsertMATRICULAS(MATRICULAS instance);
    partial void UpdateMATRICULAS(MATRICULAS instance);
    partial void DeleteMATRICULAS(MATRICULAS instance);
    partial void InsertPROFESORES(PROFESORES instance);
    partial void UpdatePROFESORES(PROFESORES instance);
    partial void DeletePROFESORES(PROFESORES instance);
    partial void InsertPROGRAMAR_CLASE(PROGRAMAR_CLASE instance);
    partial void UpdatePROGRAMAR_CLASE(PROGRAMAR_CLASE instance);
    partial void DeletePROGRAMAR_CLASE(PROGRAMAR_CLASE instance);
    partial void InsertUSUARIOS(USUARIOS instance);
    partial void UpdateUSUARIOS(USUARIOS instance);
    partial void DeleteUSUARIOS(USUARIOS instance);
    #endregion
		
		public Bd_POODataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PROYECTO_POOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Bd_POODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Bd_POODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Bd_POODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Bd_POODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CERTIFICADOS_PROFESORES> CERTIFICADOS_PROFESORES
		{
			get
			{
				return this.GetTable<CERTIFICADOS_PROFESORES>();
			}
		}
		
		public System.Data.Linq.Table<DETALLE_MATRICULA> DETALLE_MATRICULA
		{
			get
			{
				return this.GetTable<DETALLE_MATRICULA>();
			}
		}
		
		public System.Data.Linq.Table<DIAS_FERIADOS> DIAS_FERIADOS
		{
			get
			{
				return this.GetTable<DIAS_FERIADOS>();
			}
		}
		
		public System.Data.Linq.Table<ESTUDIANTES> ESTUDIANTES
		{
			get
			{
				return this.GetTable<ESTUDIANTES>();
			}
		}
		
		public System.Data.Linq.Table<HORARIO_P> HORARIO_P
		{
			get
			{
				return this.GetTable<HORARIO_P>();
			}
		}
		
		public System.Data.Linq.Table<MATERIAS> MATERIAS
		{
			get
			{
				return this.GetTable<MATERIAS>();
			}
		}
		
		public System.Data.Linq.Table<MATERIAS_ABIERTAS> MATERIAS_ABIERTAS
		{
			get
			{
				return this.GetTable<MATERIAS_ABIERTAS>();
			}
		}
		
		public System.Data.Linq.Table<MATRICULAS> MATRICULAS
		{
			get
			{
				return this.GetTable<MATRICULAS>();
			}
		}
		
		public System.Data.Linq.Table<PROFESORES> PROFESORES
		{
			get
			{
				return this.GetTable<PROFESORES>();
			}
		}
		
		public System.Data.Linq.Table<PROGRAMAR_CLASE> PROGRAMAR_CLASE
		{
			get
			{
				return this.GetTable<PROGRAMAR_CLASE>();
			}
		}
		
		public System.Data.Linq.Table<USUARIOS> USUARIOS
		{
			get
			{
				return this.GetTable<USUARIOS>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.REVISAR_DISPONIBILIDAD")]
		public int REVISAR_DISPONIBILIDAD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string dia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> hora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, dia, hora, fecha, msj);
			msj = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HORARIO_PROFESOR_VERFICACIONES")]
		public int HORARIO_PROFESOR_VERFICACIONES([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_ENTRADA", DbType="Time")] System.Nullable<System.TimeSpan> hORA_ENTRADA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_SALIDA", DbType="Time")] System.Nullable<System.TimeSpan> hORA_SALIDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIA", DbType="VarChar(20)")] string dIA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, hORA_ENTRADA, hORA_SALIDA, dIA, msj);
			msj = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_PROFESOR")]
		public int ELIMINAR_PROFESOR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_MATRICULA")]
		public int ELIMINAR_MATRICULA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_MATERIA_ABIERTA")]
		public int ELIMINAR_MATERIA_ABIERTA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_MATERIA")]
		public int ELIMINAR_MATERIA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_HORARIO")]
		public int ELIMINAR_HORARIO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_DIAS_NO_LECTIVOS")]
		public int ELIMINAR_DIAS_NO_LECTIVOS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_DETALLE")]
		public int ELIMINAR_DETALLE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR_CERTIFICADO")]
		public int ELIMINAR_CERTIFICADO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR")]
		public int ELIMINAR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CORROBORAR_USUARIOS")]
		public int CORROBORAR_USUARIOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_USER", DbType="VarChar(30)")] string nOMBRE_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRA", DbType="VarChar(20)")] string cONTRA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERMISO", DbType="VarChar(50)")] ref string pERMISO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_USER, cONTRA, pERMISO);
			pERMISO = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CORROBORAR_ESTADO")]
		public int CORROBORAR_ESTADO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Corroborar_cupo")]
		public int Corroborar_cupo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_PROFESORES")]
		public int ACTUALIZAR_PROFESORES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(30)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_P", DbType="VarChar(30)")] string nOMBRE_P, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO1_P", DbType="VarChar(30)")] string aPELLIDO1_P, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO2_P", DbType="VarChar(30)")] string aPELLIDO2_P, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO_P", DbType="VarChar(30)")] string cORREO_ELECTRONICO_P, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_TELEFONICO_P", DbType="VarChar(30)")] string nUMERO_TELEFONICO_P, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nOMBRE_P, aPELLIDO1_P, aPELLIDO2_P, cORREO_ELECTRONICO_P, nUMERO_TELEFONICO_P, msj);
			msj = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_MATRICULAS")]
		public int ACTUALIZAR_MATRICULAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MATRICULA", DbType="Int")] System.Nullable<int> iD_MATRICULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTUDIANTE", DbType="VarChar(30)")] string iD_ESTUDIANTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENCARGADO", DbType="VarChar(30)")] string eNCARGADO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MATRICULA, iD_ESTUDIANTE, eNCARGADO, msj);
			msj = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_MATERIAS_ABIERTAS")]
		public int ACTUALIZAR_MATERIAS_ABIERTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_MATERIA_ABIERTA", DbType="VarChar(20)")] string cOD_MATERIA_ABIERTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_MATERIA", DbType="VarChar(20)")] string cOD_MATERIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDENTIFICACION_P", DbType="VarChar(20)")] string iDENTIFICACION_P, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUPO", DbType="Int")] System.Nullable<int> cUPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COSTO", DbType="Int")] System.Nullable<int> cOSTO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cOD_MATERIA_ABIERTA, cOD_MATERIA, iDENTIFICACION_P, cUPO, cOSTO, msj);
			msj = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_MATERIAS")]
		public int ACTUALIZAR_MATERIAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_MATERIA", DbType="VarChar(30)")] string cOD_MATERIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_MATERIA", DbType="VarChar(50)")] string nOMBRE_MATERIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOTAL_HORAS_MATERIA", DbType="Int")] System.Nullable<int> tOTAL_HORAS_MATERIA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cOD_MATERIA, nOMBRE_MATERIA, tOTAL_HORAS_MATERIA, msj);
			msj = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_MATERIA_ABIERTA")]
		public int ACTUALIZAR_MATERIA_ABIERTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_MATERIA_ABIERTA", DbType="VarChar(20)")] string cOD_MATERIA_ABIERTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_MATERIA", DbType="VarChar(20)")] string cOD_MATERIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDENTIFICACION_P", DbType="VarChar(20)")] string iDENTIFICACION_P, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUPO", DbType="Int")] System.Nullable<int> cUPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COSTO", DbType="Int")] System.Nullable<int> cOSTO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cOD_MATERIA_ABIERTA, cOD_MATERIA, iDENTIFICACION_P, cUPO, cOSTO, msj);
			msj = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_ESTUDIANTES")]
		public int ACTUALIZAR_ESTUDIANTES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(30)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_E", DbType="VarChar(30)")] string nOMBRE_E, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO1_E", DbType="VarChar(30)")] string aPELLIDO1_E, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO2_E", DbType="VarChar(30)")] string aPELLIDO2_E, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO_E", DbType="VarChar(30)")] string cORREO_ELECTRONICO_E, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_TELEFONICO", DbType="VarChar(30)")] string nUMERO_TELEFONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nOMBRE_E, aPELLIDO1_E, aPELLIDO2_E, cORREO_ELECTRONICO_E, nUMERO_TELEFONICO, msj);
			msj = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_DETALLE_MATRICULAS")]
		public int ACTUALIZAR_DETALLE_MATRICULAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_DETALLEMATRICULA", DbType="Int")] System.Nullable<int> iD_DETALLEMATRICULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MATRICULA", DbType="Int")] System.Nullable<int> iD_MATRICULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_MATERIA_ABIERTA", DbType="VarChar(30)")] string cOD_MATERIA_ABIERTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTA", DbType="Int")] System.Nullable<int> nOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANCELADO", DbType="VarChar(30)")] string cANCELADO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_DETALLEMATRICULA, iD_MATRICULA, cOD_MATERIA_ABIERTA, nOTA, cANCELADO, msj);
			msj = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CERTIFICADOS_PROFESORES")]
	public partial class CERTIFICADOS_PROFESORES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _COD_CERTIFICADO;
		
		private string _IDENTIFICACION_P;
		
		private string _NOMBRE_CERTIFICADO;
		
		private EntityRef<PROFESORES> _PROFESORES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOD_CERTIFICADOChanging(string value);
    partial void OnCOD_CERTIFICADOChanged();
    partial void OnIDENTIFICACION_PChanging(string value);
    partial void OnIDENTIFICACION_PChanged();
    partial void OnNOMBRE_CERTIFICADOChanging(string value);
    partial void OnNOMBRE_CERTIFICADOChanged();
    #endregion
		
		public CERTIFICADOS_PROFESORES()
		{
			this._PROFESORES = default(EntityRef<PROFESORES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_CERTIFICADO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string COD_CERTIFICADO
		{
			get
			{
				return this._COD_CERTIFICADO;
			}
			set
			{
				if ((this._COD_CERTIFICADO != value))
				{
					this.OnCOD_CERTIFICADOChanging(value);
					this.SendPropertyChanging();
					this._COD_CERTIFICADO = value;
					this.SendPropertyChanged("COD_CERTIFICADO");
					this.OnCOD_CERTIFICADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICACION_P", DbType="VarChar(20)")]
		public string IDENTIFICACION_P
		{
			get
			{
				return this._IDENTIFICACION_P;
			}
			set
			{
				if ((this._IDENTIFICACION_P != value))
				{
					if (this._PROFESORES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDENTIFICACION_PChanging(value);
					this.SendPropertyChanging();
					this._IDENTIFICACION_P = value;
					this.SendPropertyChanged("IDENTIFICACION_P");
					this.OnIDENTIFICACION_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CERTIFICADO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CERTIFICADO
		{
			get
			{
				return this._NOMBRE_CERTIFICADO;
			}
			set
			{
				if ((this._NOMBRE_CERTIFICADO != value))
				{
					this.OnNOMBRE_CERTIFICADOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_CERTIFICADO = value;
					this.SendPropertyChanged("NOMBRE_CERTIFICADO");
					this.OnNOMBRE_CERTIFICADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_CERTIFICADOS_PROFESORES", Storage="_PROFESORES", ThisKey="IDENTIFICACION_P", OtherKey="IDENTIFICACION_P", IsForeignKey=true)]
		public PROFESORES PROFESORES
		{
			get
			{
				return this._PROFESORES.Entity;
			}
			set
			{
				PROFESORES previousValue = this._PROFESORES.Entity;
				if (((previousValue != value) 
							|| (this._PROFESORES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROFESORES.Entity = null;
						previousValue.CERTIFICADOS_PROFESORES.Remove(this);
					}
					this._PROFESORES.Entity = value;
					if ((value != null))
					{
						value.CERTIFICADOS_PROFESORES.Add(this);
						this._IDENTIFICACION_P = value.IDENTIFICACION_P;
					}
					else
					{
						this._IDENTIFICACION_P = default(string);
					}
					this.SendPropertyChanged("PROFESORES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALLE_MATRICULA")]
	public partial class DETALLE_MATRICULA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DETALLEMATRICULA;
		
		private int _ID_MATRICULA;
		
		private string _COD_MATERIA_ABIERTA;
		
		private int _NOTA;
		
		private string _CANCELADO;
		
		private EntityRef<MATERIAS_ABIERTAS> _MATERIAS_ABIERTAS;
		
		private EntityRef<MATRICULAS> _MATRICULAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DETALLEMATRICULAChanging(int value);
    partial void OnID_DETALLEMATRICULAChanged();
    partial void OnID_MATRICULAChanging(int value);
    partial void OnID_MATRICULAChanged();
    partial void OnCOD_MATERIA_ABIERTAChanging(string value);
    partial void OnCOD_MATERIA_ABIERTAChanged();
    partial void OnNOTAChanging(int value);
    partial void OnNOTAChanged();
    partial void OnCANCELADOChanging(string value);
    partial void OnCANCELADOChanged();
    #endregion
		
		public DETALLE_MATRICULA()
		{
			this._MATERIAS_ABIERTAS = default(EntityRef<MATERIAS_ABIERTAS>);
			this._MATRICULAS = default(EntityRef<MATRICULAS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETALLEMATRICULA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DETALLEMATRICULA
		{
			get
			{
				return this._ID_DETALLEMATRICULA;
			}
			set
			{
				if ((this._ID_DETALLEMATRICULA != value))
				{
					this.OnID_DETALLEMATRICULAChanging(value);
					this.SendPropertyChanging();
					this._ID_DETALLEMATRICULA = value;
					this.SendPropertyChanged("ID_DETALLEMATRICULA");
					this.OnID_DETALLEMATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MATRICULA", DbType="Int NOT NULL")]
		public int ID_MATRICULA
		{
			get
			{
				return this._ID_MATRICULA;
			}
			set
			{
				if ((this._ID_MATRICULA != value))
				{
					if (this._MATRICULAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MATRICULAChanging(value);
					this.SendPropertyChanging();
					this._ID_MATRICULA = value;
					this.SendPropertyChanged("ID_MATRICULA");
					this.OnID_MATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_MATERIA_ABIERTA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string COD_MATERIA_ABIERTA
		{
			get
			{
				return this._COD_MATERIA_ABIERTA;
			}
			set
			{
				if ((this._COD_MATERIA_ABIERTA != value))
				{
					if (this._MATERIAS_ABIERTAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOD_MATERIA_ABIERTAChanging(value);
					this.SendPropertyChanging();
					this._COD_MATERIA_ABIERTA = value;
					this.SendPropertyChanged("COD_MATERIA_ABIERTA");
					this.OnCOD_MATERIA_ABIERTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTA", DbType="Int NOT NULL")]
		public int NOTA
		{
			get
			{
				return this._NOTA;
			}
			set
			{
				if ((this._NOTA != value))
				{
					this.OnNOTAChanging(value);
					this.SendPropertyChanging();
					this._NOTA = value;
					this.SendPropertyChanged("NOTA");
					this.OnNOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCELADO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CANCELADO
		{
			get
			{
				return this._CANCELADO;
			}
			set
			{
				if ((this._CANCELADO != value))
				{
					this.OnCANCELADOChanging(value);
					this.SendPropertyChanging();
					this._CANCELADO = value;
					this.SendPropertyChanged("CANCELADO");
					this.OnCANCELADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_ABIERTAS_DETALLE_MATRICULA", Storage="_MATERIAS_ABIERTAS", ThisKey="COD_MATERIA_ABIERTA", OtherKey="COD_MATERIA_ABIERTA", IsForeignKey=true)]
		public MATERIAS_ABIERTAS MATERIAS_ABIERTAS
		{
			get
			{
				return this._MATERIAS_ABIERTAS.Entity;
			}
			set
			{
				MATERIAS_ABIERTAS previousValue = this._MATERIAS_ABIERTAS.Entity;
				if (((previousValue != value) 
							|| (this._MATERIAS_ABIERTAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATERIAS_ABIERTAS.Entity = null;
						previousValue.DETALLE_MATRICULA.Remove(this);
					}
					this._MATERIAS_ABIERTAS.Entity = value;
					if ((value != null))
					{
						value.DETALLE_MATRICULA.Add(this);
						this._COD_MATERIA_ABIERTA = value.COD_MATERIA_ABIERTA;
					}
					else
					{
						this._COD_MATERIA_ABIERTA = default(string);
					}
					this.SendPropertyChanged("MATERIAS_ABIERTAS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATRICULAS_DETALLE_MATRICULA", Storage="_MATRICULAS", ThisKey="ID_MATRICULA", OtherKey="ID_MATRICULA", IsForeignKey=true)]
		public MATRICULAS MATRICULAS
		{
			get
			{
				return this._MATRICULAS.Entity;
			}
			set
			{
				MATRICULAS previousValue = this._MATRICULAS.Entity;
				if (((previousValue != value) 
							|| (this._MATRICULAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATRICULAS.Entity = null;
						previousValue.DETALLE_MATRICULA.Remove(this);
					}
					this._MATRICULAS.Entity = value;
					if ((value != null))
					{
						value.DETALLE_MATRICULA.Add(this);
						this._ID_MATRICULA = value.ID_MATRICULA;
					}
					else
					{
						this._ID_MATRICULA = default(int);
					}
					this.SendPropertyChanged("MATRICULAS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIAS_FERIADOS")]
	public partial class DIAS_FERIADOS
	{
		
		private System.Nullable<System.DateTime> _FECHA;
		
		private string _MOTIVO;
		
		public DIAS_FERIADOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this._FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTIVO", DbType="VarChar(20)")]
		public string MOTIVO
		{
			get
			{
				return this._MOTIVO;
			}
			set
			{
				if ((this._MOTIVO != value))
				{
					this._MOTIVO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ESTUDIANTES")]
	public partial class ESTUDIANTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_Est;
		
		private string _IDENTIFICACION_E;
		
		private string _NOMBRE_E;
		
		private string _APELLIDO1_E;
		
		private string _APELLIDO2_E;
		
		private string _CORREO_ELECTRONICO_E;
		
		private string _NUMERO_TELEFONICO;
		
		private EntitySet<MATRICULAS> _MATRICULAS;
		
		private EntitySet<PROGRAMAR_CLASE> _PROGRAMAR_CLASE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_EstChanging(int value);
    partial void Oncod_EstChanged();
    partial void OnIDENTIFICACION_EChanging(string value);
    partial void OnIDENTIFICACION_EChanged();
    partial void OnNOMBRE_EChanging(string value);
    partial void OnNOMBRE_EChanged();
    partial void OnAPELLIDO1_EChanging(string value);
    partial void OnAPELLIDO1_EChanged();
    partial void OnAPELLIDO2_EChanging(string value);
    partial void OnAPELLIDO2_EChanged();
    partial void OnCORREO_ELECTRONICO_EChanging(string value);
    partial void OnCORREO_ELECTRONICO_EChanged();
    partial void OnNUMERO_TELEFONICOChanging(string value);
    partial void OnNUMERO_TELEFONICOChanged();
    #endregion
		
		public ESTUDIANTES()
		{
			this._MATRICULAS = new EntitySet<MATRICULAS>(new Action<MATRICULAS>(this.attach_MATRICULAS), new Action<MATRICULAS>(this.detach_MATRICULAS));
			this._PROGRAMAR_CLASE = new EntitySet<PROGRAMAR_CLASE>(new Action<PROGRAMAR_CLASE>(this.attach_PROGRAMAR_CLASE), new Action<PROGRAMAR_CLASE>(this.detach_PROGRAMAR_CLASE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_Est", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int cod_Est
		{
			get
			{
				return this._cod_Est;
			}
			set
			{
				if ((this._cod_Est != value))
				{
					this.Oncod_EstChanging(value);
					this.SendPropertyChanging();
					this._cod_Est = value;
					this.SendPropertyChanged("cod_Est");
					this.Oncod_EstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICACION_E", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDENTIFICACION_E
		{
			get
			{
				return this._IDENTIFICACION_E;
			}
			set
			{
				if ((this._IDENTIFICACION_E != value))
				{
					this.OnIDENTIFICACION_EChanging(value);
					this.SendPropertyChanging();
					this._IDENTIFICACION_E = value;
					this.SendPropertyChanged("IDENTIFICACION_E");
					this.OnIDENTIFICACION_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_E", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NOMBRE_E
		{
			get
			{
				return this._NOMBRE_E;
			}
			set
			{
				if ((this._NOMBRE_E != value))
				{
					this.OnNOMBRE_EChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_E = value;
					this.SendPropertyChanged("NOMBRE_E");
					this.OnNOMBRE_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO1_E", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string APELLIDO1_E
		{
			get
			{
				return this._APELLIDO1_E;
			}
			set
			{
				if ((this._APELLIDO1_E != value))
				{
					this.OnAPELLIDO1_EChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO1_E = value;
					this.SendPropertyChanged("APELLIDO1_E");
					this.OnAPELLIDO1_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO2_E", DbType="VarChar(20)")]
		public string APELLIDO2_E
		{
			get
			{
				return this._APELLIDO2_E;
			}
			set
			{
				if ((this._APELLIDO2_E != value))
				{
					this.OnAPELLIDO2_EChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO2_E = value;
					this.SendPropertyChanged("APELLIDO2_E");
					this.OnAPELLIDO2_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO_E", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO_E
		{
			get
			{
				return this._CORREO_ELECTRONICO_E;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO_E != value))
				{
					this.OnCORREO_ELECTRONICO_EChanging(value);
					this.SendPropertyChanging();
					this._CORREO_ELECTRONICO_E = value;
					this.SendPropertyChanged("CORREO_ELECTRONICO_E");
					this.OnCORREO_ELECTRONICO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_TELEFONICO", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string NUMERO_TELEFONICO
		{
			get
			{
				return this._NUMERO_TELEFONICO;
			}
			set
			{
				if ((this._NUMERO_TELEFONICO != value))
				{
					this.OnNUMERO_TELEFONICOChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_TELEFONICO = value;
					this.SendPropertyChanged("NUMERO_TELEFONICO");
					this.OnNUMERO_TELEFONICOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_MATRICULAS", Storage="_MATRICULAS", ThisKey="IDENTIFICACION_E", OtherKey="ID_ESTUDIANTE")]
		public EntitySet<MATRICULAS> MATRICULAS
		{
			get
			{
				return this._MATRICULAS;
			}
			set
			{
				this._MATRICULAS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_PROGRAMAR_CLASE", Storage="_PROGRAMAR_CLASE", ThisKey="IDENTIFICACION_E", OtherKey="ID_ESTUDIANTE")]
		public EntitySet<PROGRAMAR_CLASE> PROGRAMAR_CLASE
		{
			get
			{
				return this._PROGRAMAR_CLASE;
			}
			set
			{
				this._PROGRAMAR_CLASE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MATRICULAS(MATRICULAS entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = this;
		}
		
		private void detach_MATRICULAS(MATRICULAS entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = null;
		}
		
		private void attach_PROGRAMAR_CLASE(PROGRAMAR_CLASE entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = this;
		}
		
		private void detach_PROGRAMAR_CLASE(PROGRAMAR_CLASE entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HORARIO_P")]
	public partial class HORARIO_P : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HORARIO;
		
		private string _IDENTIFICACION_P;
		
		private string _DIA;
		
		private System.Nullable<System.TimeSpan> _HORA_ENTRADA;
		
		private System.Nullable<System.TimeSpan> _HORA_SALIDA;
		
		private EntityRef<PROFESORES> _PROFESORES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HORARIOChanging(int value);
    partial void OnID_HORARIOChanged();
    partial void OnIDENTIFICACION_PChanging(string value);
    partial void OnIDENTIFICACION_PChanged();
    partial void OnDIAChanging(string value);
    partial void OnDIAChanged();
    partial void OnHORA_ENTRADAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORA_ENTRADAChanged();
    partial void OnHORA_SALIDAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORA_SALIDAChanged();
    #endregion
		
		public HORARIO_P()
		{
			this._PROFESORES = default(EntityRef<PROFESORES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HORARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HORARIO
		{
			get
			{
				return this._ID_HORARIO;
			}
			set
			{
				if ((this._ID_HORARIO != value))
				{
					this.OnID_HORARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_HORARIO = value;
					this.SendPropertyChanged("ID_HORARIO");
					this.OnID_HORARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICACION_P", DbType="VarChar(20)")]
		public string IDENTIFICACION_P
		{
			get
			{
				return this._IDENTIFICACION_P;
			}
			set
			{
				if ((this._IDENTIFICACION_P != value))
				{
					if (this._PROFESORES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDENTIFICACION_PChanging(value);
					this.SendPropertyChanging();
					this._IDENTIFICACION_P = value;
					this.SendPropertyChanged("IDENTIFICACION_P");
					this.OnIDENTIFICACION_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA", DbType="VarChar(20)")]
		public string DIA
		{
			get
			{
				return this._DIA;
			}
			set
			{
				if ((this._DIA != value))
				{
					this.OnDIAChanging(value);
					this.SendPropertyChanging();
					this._DIA = value;
					this.SendPropertyChanged("DIA");
					this.OnDIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_ENTRADA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_ENTRADA
		{
			get
			{
				return this._HORA_ENTRADA;
			}
			set
			{
				if ((this._HORA_ENTRADA != value))
				{
					this.OnHORA_ENTRADAChanging(value);
					this.SendPropertyChanging();
					this._HORA_ENTRADA = value;
					this.SendPropertyChanged("HORA_ENTRADA");
					this.OnHORA_ENTRADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_SALIDA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_SALIDA
		{
			get
			{
				return this._HORA_SALIDA;
			}
			set
			{
				if ((this._HORA_SALIDA != value))
				{
					this.OnHORA_SALIDAChanging(value);
					this.SendPropertyChanging();
					this._HORA_SALIDA = value;
					this.SendPropertyChanged("HORA_SALIDA");
					this.OnHORA_SALIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_HORARIO_P", Storage="_PROFESORES", ThisKey="IDENTIFICACION_P", OtherKey="IDENTIFICACION_P", IsForeignKey=true)]
		public PROFESORES PROFESORES
		{
			get
			{
				return this._PROFESORES.Entity;
			}
			set
			{
				PROFESORES previousValue = this._PROFESORES.Entity;
				if (((previousValue != value) 
							|| (this._PROFESORES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROFESORES.Entity = null;
						previousValue.HORARIO_P.Remove(this);
					}
					this._PROFESORES.Entity = value;
					if ((value != null))
					{
						value.HORARIO_P.Add(this);
						this._IDENTIFICACION_P = value.IDENTIFICACION_P;
					}
					else
					{
						this._IDENTIFICACION_P = default(string);
					}
					this.SendPropertyChanged("PROFESORES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATERIAS")]
	public partial class MATERIAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _COD_MATERIA;
		
		private string _NOMBRE_MATERIA;
		
		private int _TOTAL_HORAS_MATERIA;
		
		private EntitySet<MATERIAS_ABIERTAS> _MATERIAS_ABIERTAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOD_MATERIAChanging(string value);
    partial void OnCOD_MATERIAChanged();
    partial void OnNOMBRE_MATERIAChanging(string value);
    partial void OnNOMBRE_MATERIAChanged();
    partial void OnTOTAL_HORAS_MATERIAChanging(int value);
    partial void OnTOTAL_HORAS_MATERIAChanged();
    #endregion
		
		public MATERIAS()
		{
			this._MATERIAS_ABIERTAS = new EntitySet<MATERIAS_ABIERTAS>(new Action<MATERIAS_ABIERTAS>(this.attach_MATERIAS_ABIERTAS), new Action<MATERIAS_ABIERTAS>(this.detach_MATERIAS_ABIERTAS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_MATERIA", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string COD_MATERIA
		{
			get
			{
				return this._COD_MATERIA;
			}
			set
			{
				if ((this._COD_MATERIA != value))
				{
					this.OnCOD_MATERIAChanging(value);
					this.SendPropertyChanging();
					this._COD_MATERIA = value;
					this.SendPropertyChanged("COD_MATERIA");
					this.OnCOD_MATERIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MATERIA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MATERIA
		{
			get
			{
				return this._NOMBRE_MATERIA;
			}
			set
			{
				if ((this._NOMBRE_MATERIA != value))
				{
					this.OnNOMBRE_MATERIAChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_MATERIA = value;
					this.SendPropertyChanged("NOMBRE_MATERIA");
					this.OnNOMBRE_MATERIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_HORAS_MATERIA", DbType="Int NOT NULL")]
		public int TOTAL_HORAS_MATERIA
		{
			get
			{
				return this._TOTAL_HORAS_MATERIA;
			}
			set
			{
				if ((this._TOTAL_HORAS_MATERIA != value))
				{
					this.OnTOTAL_HORAS_MATERIAChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_HORAS_MATERIA = value;
					this.SendPropertyChanged("TOTAL_HORAS_MATERIA");
					this.OnTOTAL_HORAS_MATERIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_MATERIAS_ABIERTAS", Storage="_MATERIAS_ABIERTAS", ThisKey="COD_MATERIA", OtherKey="COD_MATERIA")]
		public EntitySet<MATERIAS_ABIERTAS> MATERIAS_ABIERTAS
		{
			get
			{
				return this._MATERIAS_ABIERTAS;
			}
			set
			{
				this._MATERIAS_ABIERTAS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MATERIAS_ABIERTAS(MATERIAS_ABIERTAS entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS = this;
		}
		
		private void detach_MATERIAS_ABIERTAS(MATERIAS_ABIERTAS entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATERIAS_ABIERTAS")]
	public partial class MATERIAS_ABIERTAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _COD_MATERIA_ABIERTA;
		
		private string _COD_MATERIA;
		
		private string _IDENTIFICACION_P;
		
		private int _CUPO;
		
		private int _COSTO;
		
		private EntitySet<DETALLE_MATRICULA> _DETALLE_MATRICULA;
		
		private EntitySet<PROGRAMAR_CLASE> _PROGRAMAR_CLASE;
		
		private EntityRef<MATERIAS> _MATERIAS;
		
		private EntityRef<PROFESORES> _PROFESORES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOD_MATERIA_ABIERTAChanging(string value);
    partial void OnCOD_MATERIA_ABIERTAChanged();
    partial void OnCOD_MATERIAChanging(string value);
    partial void OnCOD_MATERIAChanged();
    partial void OnIDENTIFICACION_PChanging(string value);
    partial void OnIDENTIFICACION_PChanged();
    partial void OnCUPOChanging(int value);
    partial void OnCUPOChanged();
    partial void OnCOSTOChanging(int value);
    partial void OnCOSTOChanged();
    #endregion
		
		public MATERIAS_ABIERTAS()
		{
			this._DETALLE_MATRICULA = new EntitySet<DETALLE_MATRICULA>(new Action<DETALLE_MATRICULA>(this.attach_DETALLE_MATRICULA), new Action<DETALLE_MATRICULA>(this.detach_DETALLE_MATRICULA));
			this._PROGRAMAR_CLASE = new EntitySet<PROGRAMAR_CLASE>(new Action<PROGRAMAR_CLASE>(this.attach_PROGRAMAR_CLASE), new Action<PROGRAMAR_CLASE>(this.detach_PROGRAMAR_CLASE));
			this._MATERIAS = default(EntityRef<MATERIAS>);
			this._PROFESORES = default(EntityRef<PROFESORES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_MATERIA_ABIERTA", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string COD_MATERIA_ABIERTA
		{
			get
			{
				return this._COD_MATERIA_ABIERTA;
			}
			set
			{
				if ((this._COD_MATERIA_ABIERTA != value))
				{
					this.OnCOD_MATERIA_ABIERTAChanging(value);
					this.SendPropertyChanging();
					this._COD_MATERIA_ABIERTA = value;
					this.SendPropertyChanged("COD_MATERIA_ABIERTA");
					this.OnCOD_MATERIA_ABIERTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_MATERIA", DbType="VarChar(20)")]
		public string COD_MATERIA
		{
			get
			{
				return this._COD_MATERIA;
			}
			set
			{
				if ((this._COD_MATERIA != value))
				{
					if (this._MATERIAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOD_MATERIAChanging(value);
					this.SendPropertyChanging();
					this._COD_MATERIA = value;
					this.SendPropertyChanged("COD_MATERIA");
					this.OnCOD_MATERIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICACION_P", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IDENTIFICACION_P
		{
			get
			{
				return this._IDENTIFICACION_P;
			}
			set
			{
				if ((this._IDENTIFICACION_P != value))
				{
					if (this._PROFESORES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDENTIFICACION_PChanging(value);
					this.SendPropertyChanging();
					this._IDENTIFICACION_P = value;
					this.SendPropertyChanged("IDENTIFICACION_P");
					this.OnIDENTIFICACION_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUPO", DbType="Int NOT NULL")]
		public int CUPO
		{
			get
			{
				return this._CUPO;
			}
			set
			{
				if ((this._CUPO != value))
				{
					this.OnCUPOChanging(value);
					this.SendPropertyChanging();
					this._CUPO = value;
					this.SendPropertyChanged("CUPO");
					this.OnCUPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTO", DbType="Int NOT NULL")]
		public int COSTO
		{
			get
			{
				return this._COSTO;
			}
			set
			{
				if ((this._COSTO != value))
				{
					this.OnCOSTOChanging(value);
					this.SendPropertyChanging();
					this._COSTO = value;
					this.SendPropertyChanged("COSTO");
					this.OnCOSTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_ABIERTAS_DETALLE_MATRICULA", Storage="_DETALLE_MATRICULA", ThisKey="COD_MATERIA_ABIERTA", OtherKey="COD_MATERIA_ABIERTA")]
		public EntitySet<DETALLE_MATRICULA> DETALLE_MATRICULA
		{
			get
			{
				return this._DETALLE_MATRICULA;
			}
			set
			{
				this._DETALLE_MATRICULA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_ABIERTAS_PROGRAMAR_CLASE", Storage="_PROGRAMAR_CLASE", ThisKey="COD_MATERIA_ABIERTA", OtherKey="COD_MATERIA_ABIERTA")]
		public EntitySet<PROGRAMAR_CLASE> PROGRAMAR_CLASE
		{
			get
			{
				return this._PROGRAMAR_CLASE;
			}
			set
			{
				this._PROGRAMAR_CLASE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_MATERIAS_ABIERTAS", Storage="_MATERIAS", ThisKey="COD_MATERIA", OtherKey="COD_MATERIA", IsForeignKey=true)]
		public MATERIAS MATERIAS
		{
			get
			{
				return this._MATERIAS.Entity;
			}
			set
			{
				MATERIAS previousValue = this._MATERIAS.Entity;
				if (((previousValue != value) 
							|| (this._MATERIAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATERIAS.Entity = null;
						previousValue.MATERIAS_ABIERTAS.Remove(this);
					}
					this._MATERIAS.Entity = value;
					if ((value != null))
					{
						value.MATERIAS_ABIERTAS.Add(this);
						this._COD_MATERIA = value.COD_MATERIA;
					}
					else
					{
						this._COD_MATERIA = default(string);
					}
					this.SendPropertyChanged("MATERIAS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_MATERIAS_ABIERTAS", Storage="_PROFESORES", ThisKey="IDENTIFICACION_P", OtherKey="IDENTIFICACION_P", IsForeignKey=true)]
		public PROFESORES PROFESORES
		{
			get
			{
				return this._PROFESORES.Entity;
			}
			set
			{
				PROFESORES previousValue = this._PROFESORES.Entity;
				if (((previousValue != value) 
							|| (this._PROFESORES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROFESORES.Entity = null;
						previousValue.MATERIAS_ABIERTAS.Remove(this);
					}
					this._PROFESORES.Entity = value;
					if ((value != null))
					{
						value.MATERIAS_ABIERTAS.Add(this);
						this._IDENTIFICACION_P = value.IDENTIFICACION_P;
					}
					else
					{
						this._IDENTIFICACION_P = default(string);
					}
					this.SendPropertyChanged("PROFESORES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_MATRICULA(DETALLE_MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS_ABIERTAS = this;
		}
		
		private void detach_DETALLE_MATRICULA(DETALLE_MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS_ABIERTAS = null;
		}
		
		private void attach_PROGRAMAR_CLASE(PROGRAMAR_CLASE entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS_ABIERTAS = this;
		}
		
		private void detach_PROGRAMAR_CLASE(PROGRAMAR_CLASE entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS_ABIERTAS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATRICULAS")]
	public partial class MATRICULAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MATRICULA;
		
		private string _ID_ESTUDIANTE;
		
		private System.DateTime _FECHA;
		
		private string _ENCARGADO;
		
		private EntitySet<DETALLE_MATRICULA> _DETALLE_MATRICULA;
		
		private EntityRef<ESTUDIANTES> _ESTUDIANTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MATRICULAChanging(int value);
    partial void OnID_MATRICULAChanged();
    partial void OnID_ESTUDIANTEChanging(string value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnFECHAChanging(System.DateTime value);
    partial void OnFECHAChanged();
    partial void OnENCARGADOChanging(string value);
    partial void OnENCARGADOChanged();
    #endregion
		
		public MATRICULAS()
		{
			this._DETALLE_MATRICULA = new EntitySet<DETALLE_MATRICULA>(new Action<DETALLE_MATRICULA>(this.attach_DETALLE_MATRICULA), new Action<DETALLE_MATRICULA>(this.detach_DETALLE_MATRICULA));
			this._ESTUDIANTES = default(EntityRef<ESTUDIANTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MATRICULA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_MATRICULA
		{
			get
			{
				return this._ID_MATRICULA;
			}
			set
			{
				if ((this._ID_MATRICULA != value))
				{
					this.OnID_MATRICULAChanging(value);
					this.SendPropertyChanging();
					this._ID_MATRICULA = value;
					this.SendPropertyChanged("ID_MATRICULA");
					this.OnID_MATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					if (this._ESTUDIANTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="Date NOT NULL")]
		public System.DateTime FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENCARGADO", DbType="VarChar(25)")]
		public string ENCARGADO
		{
			get
			{
				return this._ENCARGADO;
			}
			set
			{
				if ((this._ENCARGADO != value))
				{
					this.OnENCARGADOChanging(value);
					this.SendPropertyChanging();
					this._ENCARGADO = value;
					this.SendPropertyChanged("ENCARGADO");
					this.OnENCARGADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATRICULAS_DETALLE_MATRICULA", Storage="_DETALLE_MATRICULA", ThisKey="ID_MATRICULA", OtherKey="ID_MATRICULA")]
		public EntitySet<DETALLE_MATRICULA> DETALLE_MATRICULA
		{
			get
			{
				return this._DETALLE_MATRICULA;
			}
			set
			{
				this._DETALLE_MATRICULA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_MATRICULAS", Storage="_ESTUDIANTES", ThisKey="ID_ESTUDIANTE", OtherKey="IDENTIFICACION_E", IsForeignKey=true)]
		public ESTUDIANTES ESTUDIANTES
		{
			get
			{
				return this._ESTUDIANTES.Entity;
			}
			set
			{
				ESTUDIANTES previousValue = this._ESTUDIANTES.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTES.Entity = null;
						previousValue.MATRICULAS.Remove(this);
					}
					this._ESTUDIANTES.Entity = value;
					if ((value != null))
					{
						value.MATRICULAS.Add(this);
						this._ID_ESTUDIANTE = value.IDENTIFICACION_E;
					}
					else
					{
						this._ID_ESTUDIANTE = default(string);
					}
					this.SendPropertyChanged("ESTUDIANTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_MATRICULA(DETALLE_MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.MATRICULAS = this;
		}
		
		private void detach_DETALLE_MATRICULA(DETALLE_MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.MATRICULAS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROFESORES")]
	public partial class PROFESORES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDENTIFICACION_P;
		
		private string _NOMBRE_P;
		
		private string _APELLIDO1_P;
		
		private string _APELLIDO2_P;
		
		private string _CORREO_ELECTRONICO_P;
		
		private string _NUMERO_TELEFONICO_P;
		
		private EntitySet<CERTIFICADOS_PROFESORES> _CERTIFICADOS_PROFESORES;
		
		private EntitySet<HORARIO_P> _HORARIO_P;
		
		private EntitySet<MATERIAS_ABIERTAS> _MATERIAS_ABIERTAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDENTIFICACION_PChanging(string value);
    partial void OnIDENTIFICACION_PChanged();
    partial void OnNOMBRE_PChanging(string value);
    partial void OnNOMBRE_PChanged();
    partial void OnAPELLIDO1_PChanging(string value);
    partial void OnAPELLIDO1_PChanged();
    partial void OnAPELLIDO2_PChanging(string value);
    partial void OnAPELLIDO2_PChanged();
    partial void OnCORREO_ELECTRONICO_PChanging(string value);
    partial void OnCORREO_ELECTRONICO_PChanged();
    partial void OnNUMERO_TELEFONICO_PChanging(string value);
    partial void OnNUMERO_TELEFONICO_PChanged();
    #endregion
		
		public PROFESORES()
		{
			this._CERTIFICADOS_PROFESORES = new EntitySet<CERTIFICADOS_PROFESORES>(new Action<CERTIFICADOS_PROFESORES>(this.attach_CERTIFICADOS_PROFESORES), new Action<CERTIFICADOS_PROFESORES>(this.detach_CERTIFICADOS_PROFESORES));
			this._HORARIO_P = new EntitySet<HORARIO_P>(new Action<HORARIO_P>(this.attach_HORARIO_P), new Action<HORARIO_P>(this.detach_HORARIO_P));
			this._MATERIAS_ABIERTAS = new EntitySet<MATERIAS_ABIERTAS>(new Action<MATERIAS_ABIERTAS>(this.attach_MATERIAS_ABIERTAS), new Action<MATERIAS_ABIERTAS>(this.detach_MATERIAS_ABIERTAS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICACION_P", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDENTIFICACION_P
		{
			get
			{
				return this._IDENTIFICACION_P;
			}
			set
			{
				if ((this._IDENTIFICACION_P != value))
				{
					this.OnIDENTIFICACION_PChanging(value);
					this.SendPropertyChanging();
					this._IDENTIFICACION_P = value;
					this.SendPropertyChanged("IDENTIFICACION_P");
					this.OnIDENTIFICACION_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_P", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NOMBRE_P
		{
			get
			{
				return this._NOMBRE_P;
			}
			set
			{
				if ((this._NOMBRE_P != value))
				{
					this.OnNOMBRE_PChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_P = value;
					this.SendPropertyChanged("NOMBRE_P");
					this.OnNOMBRE_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO1_P", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string APELLIDO1_P
		{
			get
			{
				return this._APELLIDO1_P;
			}
			set
			{
				if ((this._APELLIDO1_P != value))
				{
					this.OnAPELLIDO1_PChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO1_P = value;
					this.SendPropertyChanged("APELLIDO1_P");
					this.OnAPELLIDO1_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO2_P", DbType="VarChar(20)")]
		public string APELLIDO2_P
		{
			get
			{
				return this._APELLIDO2_P;
			}
			set
			{
				if ((this._APELLIDO2_P != value))
				{
					this.OnAPELLIDO2_PChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO2_P = value;
					this.SendPropertyChanged("APELLIDO2_P");
					this.OnAPELLIDO2_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO_P", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO_P
		{
			get
			{
				return this._CORREO_ELECTRONICO_P;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO_P != value))
				{
					this.OnCORREO_ELECTRONICO_PChanging(value);
					this.SendPropertyChanging();
					this._CORREO_ELECTRONICO_P = value;
					this.SendPropertyChanged("CORREO_ELECTRONICO_P");
					this.OnCORREO_ELECTRONICO_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_TELEFONICO_P", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string NUMERO_TELEFONICO_P
		{
			get
			{
				return this._NUMERO_TELEFONICO_P;
			}
			set
			{
				if ((this._NUMERO_TELEFONICO_P != value))
				{
					this.OnNUMERO_TELEFONICO_PChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_TELEFONICO_P = value;
					this.SendPropertyChanged("NUMERO_TELEFONICO_P");
					this.OnNUMERO_TELEFONICO_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_CERTIFICADOS_PROFESORES", Storage="_CERTIFICADOS_PROFESORES", ThisKey="IDENTIFICACION_P", OtherKey="IDENTIFICACION_P")]
		public EntitySet<CERTIFICADOS_PROFESORES> CERTIFICADOS_PROFESORES
		{
			get
			{
				return this._CERTIFICADOS_PROFESORES;
			}
			set
			{
				this._CERTIFICADOS_PROFESORES.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_HORARIO_P", Storage="_HORARIO_P", ThisKey="IDENTIFICACION_P", OtherKey="IDENTIFICACION_P")]
		public EntitySet<HORARIO_P> HORARIO_P
		{
			get
			{
				return this._HORARIO_P;
			}
			set
			{
				this._HORARIO_P.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_MATERIAS_ABIERTAS", Storage="_MATERIAS_ABIERTAS", ThisKey="IDENTIFICACION_P", OtherKey="IDENTIFICACION_P")]
		public EntitySet<MATERIAS_ABIERTAS> MATERIAS_ABIERTAS
		{
			get
			{
				return this._MATERIAS_ABIERTAS;
			}
			set
			{
				this._MATERIAS_ABIERTAS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CERTIFICADOS_PROFESORES(CERTIFICADOS_PROFESORES entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = this;
		}
		
		private void detach_CERTIFICADOS_PROFESORES(CERTIFICADOS_PROFESORES entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = null;
		}
		
		private void attach_HORARIO_P(HORARIO_P entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = this;
		}
		
		private void detach_HORARIO_P(HORARIO_P entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = null;
		}
		
		private void attach_MATERIAS_ABIERTAS(MATERIAS_ABIERTAS entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = this;
		}
		
		private void detach_MATERIAS_ABIERTAS(MATERIAS_ABIERTAS entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROGRAMAR_CLASE")]
	public partial class PROGRAMAR_CLASE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLASE;
		
		private string _ID_ESTUDIANTE;
		
		private string _COD_MATERIA_ABIERTA;
		
		private System.Nullable<System.DateTime> _DIA;
		
		private System.Nullable<System.TimeSpan> _HORA;
		
		private EntityRef<MATERIAS_ABIERTAS> _MATERIAS_ABIERTAS;
		
		private EntityRef<ESTUDIANTES> _ESTUDIANTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLASEChanging(int value);
    partial void OnID_CLASEChanged();
    partial void OnID_ESTUDIANTEChanging(string value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnCOD_MATERIA_ABIERTAChanging(string value);
    partial void OnCOD_MATERIA_ABIERTAChanged();
    partial void OnDIAChanging(System.Nullable<System.DateTime> value);
    partial void OnDIAChanged();
    partial void OnHORAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORAChanged();
    #endregion
		
		public PROGRAMAR_CLASE()
		{
			this._MATERIAS_ABIERTAS = default(EntityRef<MATERIAS_ABIERTAS>);
			this._ESTUDIANTES = default(EntityRef<ESTUDIANTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLASE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLASE
		{
			get
			{
				return this._ID_CLASE;
			}
			set
			{
				if ((this._ID_CLASE != value))
				{
					this.OnID_CLASEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLASE = value;
					this.SendPropertyChanged("ID_CLASE");
					this.OnID_CLASEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", DbType="VarChar(20)")]
		public string ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					if (this._ESTUDIANTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_MATERIA_ABIERTA", DbType="VarChar(20)")]
		public string COD_MATERIA_ABIERTA
		{
			get
			{
				return this._COD_MATERIA_ABIERTA;
			}
			set
			{
				if ((this._COD_MATERIA_ABIERTA != value))
				{
					if (this._MATERIAS_ABIERTAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOD_MATERIA_ABIERTAChanging(value);
					this.SendPropertyChanging();
					this._COD_MATERIA_ABIERTA = value;
					this.SendPropertyChanged("COD_MATERIA_ABIERTA");
					this.OnCOD_MATERIA_ABIERTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DIA
		{
			get
			{
				return this._DIA;
			}
			set
			{
				if ((this._DIA != value))
				{
					this.OnDIAChanging(value);
					this.SendPropertyChanging();
					this._DIA = value;
					this.SendPropertyChanged("DIA");
					this.OnDIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA
		{
			get
			{
				return this._HORA;
			}
			set
			{
				if ((this._HORA != value))
				{
					this.OnHORAChanging(value);
					this.SendPropertyChanging();
					this._HORA = value;
					this.SendPropertyChanged("HORA");
					this.OnHORAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_ABIERTAS_PROGRAMAR_CLASE", Storage="_MATERIAS_ABIERTAS", ThisKey="COD_MATERIA_ABIERTA", OtherKey="COD_MATERIA_ABIERTA", IsForeignKey=true)]
		public MATERIAS_ABIERTAS MATERIAS_ABIERTAS
		{
			get
			{
				return this._MATERIAS_ABIERTAS.Entity;
			}
			set
			{
				MATERIAS_ABIERTAS previousValue = this._MATERIAS_ABIERTAS.Entity;
				if (((previousValue != value) 
							|| (this._MATERIAS_ABIERTAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATERIAS_ABIERTAS.Entity = null;
						previousValue.PROGRAMAR_CLASE.Remove(this);
					}
					this._MATERIAS_ABIERTAS.Entity = value;
					if ((value != null))
					{
						value.PROGRAMAR_CLASE.Add(this);
						this._COD_MATERIA_ABIERTA = value.COD_MATERIA_ABIERTA;
					}
					else
					{
						this._COD_MATERIA_ABIERTA = default(string);
					}
					this.SendPropertyChanged("MATERIAS_ABIERTAS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_PROGRAMAR_CLASE", Storage="_ESTUDIANTES", ThisKey="ID_ESTUDIANTE", OtherKey="IDENTIFICACION_E", IsForeignKey=true)]
		public ESTUDIANTES ESTUDIANTES
		{
			get
			{
				return this._ESTUDIANTES.Entity;
			}
			set
			{
				ESTUDIANTES previousValue = this._ESTUDIANTES.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTES.Entity = null;
						previousValue.PROGRAMAR_CLASE.Remove(this);
					}
					this._ESTUDIANTES.Entity = value;
					if ((value != null))
					{
						value.PROGRAMAR_CLASE.Add(this);
						this._ID_ESTUDIANTE = value.IDENTIFICACION_E;
					}
					else
					{
						this._ID_ESTUDIANTE = default(string);
					}
					this.SendPropertyChanged("ESTUDIANTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIOS")]
	public partial class USUARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USER;
		
		private string _NOMBRE_USER;
		
		private string _CONTRA;
		
		private string _PERMISO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnNOMBRE_USERChanging(string value);
    partial void OnNOMBRE_USERChanged();
    partial void OnCONTRAChanging(string value);
    partial void OnCONTRAChanged();
    partial void OnPERMISOChanging(string value);
    partial void OnPERMISOChanged();
    #endregion
		
		public USUARIOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USER", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NOMBRE_USER
		{
			get
			{
				return this._NOMBRE_USER;
			}
			set
			{
				if ((this._NOMBRE_USER != value))
				{
					this.OnNOMBRE_USERChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_USER = value;
					this.SendPropertyChanged("NOMBRE_USER");
					this.OnNOMBRE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRA", DbType="VarChar(30)")]
		public string CONTRA
		{
			get
			{
				return this._CONTRA;
			}
			set
			{
				if ((this._CONTRA != value))
				{
					this.OnCONTRAChanging(value);
					this.SendPropertyChanging();
					this._CONTRA = value;
					this.SendPropertyChanged("CONTRA");
					this.OnCONTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERMISO", DbType="VarChar(30)")]
		public string PERMISO
		{
			get
			{
				return this._PERMISO;
			}
			set
			{
				if ((this._PERMISO != value))
				{
					this.OnPERMISOChanging(value);
					this.SendPropertyChanging();
					this._PERMISO = value;
					this.SendPropertyChanged("PERMISO");
					this.OnPERMISOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
